$primary_paletteKeyColor = 697b77
$secondary_paletteKeyColor = 727876
$tertiary_paletteKeyColor = 5c5968
$neutral_paletteKeyColor = 777776
$neutral_variant_paletteKeyColor = 727876
$background = fbf9f8
$onBackground = 1b1c1b
$surface = fbf9f8
$surfaceDim = dbdad8
$surfaceBright = fbf9f8
$surfaceContainerLowest = ffffff
$surfaceContainerLow = f5f3f2
$surfaceContainer = efedec
$surfaceContainerHigh = eae8e6
$surfaceContainerHighest = e4e2e1
$onSurface = 1b1c1b
$surfaceVariant = dee4e1
$onSurfaceVariant = 424846
$inverseSurface = 303030
$inverseOnSurface = f2f0ef
$outline = 707674
$outlineVariant = c2c8c5
$shadow = 000000
$scrim = 000000
$surfaceTint = 51625e
$primary = 677874
$onPrimary = ffffff
$primaryContainer = 4d5e5a
$onPrimaryContainer = c4d7d1
$inversePrimary = b8cac5
$secondary = 59605e
$onSecondary = ffffff
$secondaryContainer = dee4e1
$onSecondaryContainer = 5f6664
$tertiary = 767282
$onTertiary = ffffff
$tertiaryContainer = 767282
$onTertiaryContainer = ffffff
$error = ba1a1a
$onError = ffffff
$errorContainer = ffdad6
$onErrorContainer = 93000a
$primaryFixed = d4e7e1
$primaryFixedDim = b8cac5
$onPrimaryFixed = 0e1e1b
$onPrimaryFixedVariant = 394a46
$secondaryFixed = dee4e1
$secondaryFixedDim = c1c8c5
$onSecondaryFixed = 171d1b
$onSecondaryFixedVariant = 424846
$tertiaryFixed = e5e0f2
$tertiaryFixedDim = c9c4d6
$onTertiaryFixed = 1c1a27
$onTertiaryFixedVariant = 484553
$term0 = 9a9b99
$term1 = 686300
$term2 = 009174
$term3 = 427d3b
$term4 = 339a72
$term5 = 0071a3
$term6 = 188f86
$term7 = 1f2323
$term8 = 0f0f0f
$term9 = 817b00
$term10 = 13b592
$term11 = 5d9954
$term12 = 5bbd93
$term13 = 008cca
$term14 = 47b0a7
$term15 = 25292a
$rosewater = 6b8647
$flamingo = 6f7c1e
$pink = 0085c0
$mauve = 005e67
$red = 515900
$maroon = 606c00
$peach = 198900
$yellow = 00905c
$green = 007e67
$teal = 00756d
$sky = 008887
$sapphire = 00807a
$blue = 006468
$lavender = 007e86
$klink = 009796
$klinkSelection = 009795
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bfa1
$kpositiveSelection = 00bf9f
$text = 1b1c1b
$subtext1 = 424846
$subtext0 = 707674
$overlay2 = 818684
$overlay1 = 949796
$overlay0 = a6a9a7
$surface2 = b9bbb9
$surface1 = cdcecd
$surface0 = e4e3e2
$base = fbf9f8
$mantle = f2f1f0
$crust = ebebea
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
