$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 797675
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = f9f9f9
$onBackground = 1b1b1b
$surface = f9f9f9
$surfaceDim = dadada
$surfaceBright = f9f9f9
$surfaceContainerLowest = ffffff
$surfaceContainerLow = f3f3f3
$surfaceContainer = eeeeee
$surfaceContainerHigh = e8e8e8
$surfaceContainerHighest = e2e2e2
$onSurface = 1b1b1b
$surfaceVariant = e2e2e2
$onSurfaceVariant = 464646
$inverseSurface = 303030
$inverseOnSurface = f1f1f1
$outline = 757575
$outlineVariant = c7c7c7
$shadow = 000000
$scrim = 000000
$surfaceTint = 5e5e5e
$primary = 5e5e5e
$onPrimary = ffffff
$primaryContainer = e2e2e2
$onPrimaryContainer = 464646
$inversePrimary = c7c7c7
$secondary = 5e5e5e
$onSecondary = ffffff
$secondaryContainer = e2e2e2
$onSecondaryContainer = 474747
$tertiary = 777472
$onTertiary = ffffff
$tertiaryContainer = 777472
$onTertiaryContainer = ffffff
$error = af2f28
$onError = ffffff
$errorContainer = e2e2e2
$onErrorContainer = 891c18
$primaryFixed = e2e2e2
$primaryFixedDim = c7c7c7
$onPrimaryFixed = 1b1b1b
$onPrimaryFixedVariant = 464646
$secondaryFixed = e2e2e2
$secondaryFixedDim = c6c6c6
$onSecondaryFixed = 1c1c1c
$onSecondaryFixedVariant = 474747
$tertiaryFixed = e6e2df
$tertiaryFixedDim = cac5c3
$onTertiaryFixed = 1c1b1a
$onTertiaryFixedVariant = 484645
$term0 = 9b9b9b
$term1 = 7c5a2e
$term2 = 917f3b
$term3 = 8a6a35
$term4 = a18546
$term5 = 8c6030
$term6 = 83834e
$term7 = 222222
$term8 = 0f0f0f
$term9 = 9c7036
$term10 = b59f4c
$term11 = aa8547
$term12 = c6a865
$term13 = b17838
$term14 = a4a36b
$term15 = 282828
$rosewater = 947952
$flamingo = 966e37
$pink = a77236
$mauve = 834320
$red = 6b4f2a
$maroon = 815f30
$peach = 937037
$yellow = 99793a
$green = 7d6f35
$teal = 6c6a38
$sky = 5b8446
$sapphire = 73773e
$blue = 9e3347
$lavender = b25557
$klink = 6a9165
$klinkSelection = 6a9165
$kvisited = b27235
$kvisitedSelection = b37134
$knegative = b07e3b
$knegativeSelection = b17e3b
$kneutral = d7a147
$kneutralSelection = d8a047
$kpositive = bda948
$kpositiveSelection = bfa948
$text = 1b1b1b
$subtext1 = 464646
$subtext0 = 757575
$overlay2 = 858585
$overlay1 = 979797
$overlay0 = a8a8a8
$surface2 = bababa
$surface1 = cecece
$surface0 = e3e3e3
$base = f9f9f9
$mantle = f0f1f1
$crust = e9ebec
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
