# Reload in real-time
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Enable 256 color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# Change the prefix
set -g prefix C-a
bind C-a send-prefix -2

# Change split keybind
bind | split-window -h
bind - split-window -v

# Vim keybind
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse
set -g mouse on

# tmux plugins
# Remember to install TPM for plugins
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'

# plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Catppuccin config (status bar)
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


# Initialize tpm NOTE: Alway at the bottom
run '~/.tmux/plugins/tpm/tpm'
