# ============================================================
# Theme
# ============================================================

include current-theme.conf


# ============================================================
# Font
# ============================================================

font_family JetBrainsMono Nerd Font
font_size 16


# ============================================================
# Window
# ============================================================

window_padding_width 8 10
placement_strategy center

hide_window_decorations titlebar-only
macos_show_window_title_in none


# ============================================================
# Shell integration
# ============================================================

shell_integration enabled


# ============================================================
# Transparency / blur
# ============================================================

background_opacity 0.85
background_blur 20

# # Optional: make common Catppuccin Latte backgrounds transparent too
# transparent_background_colors #eff1f5@0.85 #e6e9ef@0.85 #dce0e8@0.85


# ============================================================
# Selection
# ============================================================

copy_on_select clipboard



# ============================================================
# No Close Confirmation
# ============================================================

confirm_os_window_close 0
