

# Special workspaces
windowrule = workspace special:sysmon, match:class btop|F5 VPN
windowrule = workspace special:music, match:class feishin|Spotify|Supersonic
windowrule = workspace special:music, match:initial_title Spotify( Free)?  # Spotify wayland, it has no class for some reason
windowrule = workspace special:communication, match:class discord|equibop|vesktop|whatsapp|wechat|Slack
windowrule = workspace special:todo, match:class Todoist|Kuro


# Zotero
windowrule = float true, match:title Zotero Settings
windowrule = float true, match:title Plugins Manager

# WeChat noborder
windowrule = match:class ^(wechat)$, match:title ^(?!朋友圈$).*, no_blur on
windowrule = match:class ^(wechat)$, match:title ^(?!朋友圈$).*, no_shadow on
windowrule = match:class ^(wechat)$, match:title ^(?!朋友圈$).*, border_size 0
