# ### Hyprland ###
# Apps
$terminal = foot
$browser = zen-browser
$editor = nvim
$fileExplorer = thunar

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = false
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 0
$windowGapsOut = 2
$singleWindowGapsOut = 1

# Window styling
$windowOpacity = 0.95
$windowRounding = 10

$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 10  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Super, bracketright
$kbPrevWs = Super, bracketleft

$kbToggleSpecialWs = Super, S

$kbWsOverview = Super, A

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super+Alt, F
$kbWindowBorderedFullscreen = Super, F
$kbToggleWindowFloating = Super, Space
$kbCloseWindow = Super, Backspace

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Super, Return
$kbBrowser = Super, B
$kbEditor = Super, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, P
$kbRestoreLock = Super+Alt, L
