decoration {
    rounding = $windowRounding
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.1

    blur {
        enabled = $blurEnabled
        xray = $blurXray
        special = $blurSpecialWs
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = $blurPopups
        input_methods = $blurInputMethods
        size = $blurSize
        passes = $blurPasses
    }

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        color = $shadowColour
    }
}
