[mgr]
ratio = [ 0, 3, 4 ]
linemode = "size_and_mtime"
sort_by = "mtime"
sort_reverse = true

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

[plugin]
prepend_previewers = [
  { url = "*.ipynb", run = "nbpreview" },
]
